version: "3"

services:
  web:
    container_name: php-apache-drupal
    image: webdevops/php-apache:alpine-php7
    ports:
      - "4500:80"
    volumes:
      - ./www:/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8004:3306
    hostname: db-local  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini