version: "3"

services:
  web:
    container_name: php-apache-php-8.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4500:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db  

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 4510:3306
    hostname: db-local  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "4520:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini