version: '3'

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8004:3306
        hostname: db-local

    php-apache-environment:
        container_name: php-apache-drupal
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - './www/:/var/www/html/'
        ports:
            - 4500:80

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
        - 8080:80
        volumes:
        - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini